name: this is the name of the github action
run-name: defaults to commit message if not specified
on: [push]
jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run : echo "hello world"
