name: matrix job
run-name: ${{ github.actor }} has initiated matrix.yml
on: [push]
jobs:
  build:
    strategy:
      matrix:
        node-version: [10, 12, 21]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: node --version
