name: series jobs
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3s && echo test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: sleep 5s && echo build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo test 
